/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gaoruishan_androidndk_JNI */

#ifndef _Included_com_gaoruishan_androidndk_JNI
#define _Included_com_gaoruishan_androidndk_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gaoruishan_androidndk_JNI
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gaoruishan_androidndk_JNI_getString__
  (JNIEnv *, jobject);

/*
 * Class:     com_gaoruishan_androidndk_JNI
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gaoruishan_androidndk_JNI_getString__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gaoruishan_androidndk_JNI
 * Method:    getInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_gaoruishan_androidndk_JNI_getInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gaoruishan_androidndk_JNI
 * Method:    getIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_gaoruishan_androidndk_JNI_getIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_gaoruishan_androidndk_JNI
 * Method:    callGet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gaoruishan_androidndk_JNI_callGet
  (JNIEnv *, jobject);

/*
 * Class:     com_gaoruishan_androidndk_JNI
 * Method:    callSetString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gaoruishan_androidndk_JNI_callSetString
  (JNIEnv *, jobject);

/*
 * Class:     com_gaoruishan_androidndk_JNI
 * Method:    callGetInt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gaoruishan_androidndk_JNI_callGetInt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
